### ISSUE TITLE
Correction Needed: Inaccurate Information on Sprinto Ignite

### ISSUE THREAD

**Issue by Karansprinto** [Rhosys/soc2.fyi#10]
Hey Team,

I hope this email finds you well. I am reaching out to address some inaccuracies in [soc2.fyi](https://soc2.fyi/)  regarding Sprinto Ignite, which have been shared on a particular platform. 

Here are the corrections and the accurate information for Sprinto Ignite:

Inaccurate Information:
The information provided about Sprinto Ignite lacks accuracy and does not properly reflect the services and benefits offered by the program.
Accurate Information:
Sprinto Ignite is a comprehensive program designed for ambitious tech startups aiming to achieve compliance efficiently and affordably. Below are the key highlights of Sprinto Ignite:

Ready-to-Launch Compliance Programs:
Sprinto Ignite offers pre-built compliance programs for standards like SOC2 and ISO27001. These programs come with ready-to-use policy templates, pre-built workflows, and expert guidance to streamline the compliance process.

Expert Guidance:
Startups enrolled in Sprinto Ignite gain access to compliance and audit experts who provide advisory support on compliance-related matters. This expert guidance is available 24/5 globally, ensuring startups receive timely assistance whenever needed.

Contactless Audit:
Sprinto Ignite facilitates contactless audits through a shared dashboard, allowing auditors to efficiently review all evidence against control measures without unnecessary back-and-forth communication.

Cost-Effective Pricing:
The program offers compelling value with pricing starting at $4,000 in the first year, followed by subsequent discounts of 60% in the second year and 40% in the third year.

Additional Platform Perks:
Participants of Sprinto Ignite enjoy various platform perks, including access to a sharable Trust Center, compliance logo placement, and a compliance promotion package. Additionally, startups unlock $50,000 worth of credits for tools and suites to aid in their growth journey.

Startup Growth Plans:
Sprinto Ignite empowers startups to achieve consistent, scalable growth by providing continuous entity monitoring capabilities, enabling them to add people, processes, policies, and technology while ensuring the highest level of data security.

Given these corrections, I kindly request that the inaccurate information be amended accordingly to provide readers with an accurate understanding of Sprinto Ignite's offerings and benefits.

Should you require any further clarification or assistance, please feel free to reach out to us or we can connect over a call.

Thank you for your attention to this matter, Looking forward to hearing from you.

Best.
Karan Arora

**Comment by wparad** [comment]
We are more than happy to accept a PR that reflects the updates to any of the incorrect data we currently track.

Thanks!

**Comment by Karansprinto** [comment]
Hey Team,

Kindly refer to this official page of Sprinto: https://sprinto.com/ignite/

You will get the correct stats.

Feel free to reach out in case you have any questions.

Looking forward to hearing from you.

Best.

**Comment by wparad** [comment]
@Karansprinto it is a full time job to correctly maintain an up to date list of all the information from all the different providers. As such we just don't have the capacity to go and extract individual pieces of information every time someone says something isn't accurate.

If you aren't willing to make a PR we at least need to receive a list of exactly which things you would want changed. That is, what exactly are the words that are not correct (including which column and section on the page) and what exactly is the correct wording.

As soon as this issue is updated, we'll get that corrected.

**Comment by GlitchWitch** [comment]
> We are more than happy to accept a PR that reflects the updates to any of the incorrect data we currently track.

> If you aren't willing to make a PR we at least need to receive a list of exactly which things you would want changed.

@wparad Just wanted to share that you are far more patient and accommodating then I would be. 

In my opinion if someone feels strongly that information is incorrect on a free and open resource that welcomes contributions, they can find the resources to bring someone in to make those contributions via a PR rather then trying to treat it like a paid advertisement by disrespecting your time and the labour you've already put into compiling this resource.

**Comment by Karansprinto** [comment]
Hey team,

This is not a paid or Advertisement.
I’ve passed on your comments internally with my team, they will share
exactly how you asked for pointing what’s wrong and what’s needed to be
done.

Best.

**Comment by Karansprinto** [comment]
Hey Team,

Kindly Find the attached Sheet
<https://docs.google.com/spreadsheets/d/1cvofXE_HrFggqq1hZT1hSxN-70DY4A5EMYC7DnWo3V0/edit?usp=sharing>
with all the Correct Information about Sprinto.

I've shared the access to this email - ***@***.***

Let me know in case you have any questions or if something is required.

Looking forward to hearing from you.

Best.

**Comment by wparad** [comment]
@Karansprinto that link doesn't work, it brings me to a log in screen: 
![image](https://github.com/Rhosys/soc2.fyi/assets/5056218/ae55d736-d694-45e4-9da7-b86d1f53d1b8)

Can you please post the details in this issue ticket so the request is adequately tracked?

Thanks,
Warren

**Comment by Karansprinto** [comment]
In case you don't have access to google tools like sheets, where else can I share?

**Comment by wparad** [comment]
> In case you don't have access to google tools like sheets, where else can I share?

@Karansprinto please paste the contents in this GitHub issue.

**Comment by Karansprinto** [comment]
<img width="1114" alt="Screenshot 2024-04-19 at 7 11 39 PM" src="https://github.com/Rhosys/soc2.fyi/assets/166333933/7806bddb-4a6a-4996-965f-5a1645d7d6f1">

**Comment by wparad** [comment]
@Karansprinto Can you link me to your site's documentation where it says you offer a $7k one year contract and the contracted auditors are included in the price, because I'm looking at the link and I can't find it.

(Re everything else, thanks for the information, I've updated the page.)

**Comment by Karansprinto** [comment]
Hey @wparad 

Thanks for the prompt reply, please find our responses below:
1. Our name is Sprinto, not Sprinto Ignite(Sprinto Ignite is a campaign we ran for a couple of quarters, it is no longer valid now). Could you please change the same?
2. We are not aggressive marketers (our total marketing budget is 1/10th of other players in the market)
3. We do not have the said documentation to attest to the same you can write audit cost as Starting from $2k
4. Pricing is determined on a case-by-case basis, it is affected by multiple variables such as No. of employees, and the frameworks one wishes to get compliance for(eg SOC2, GDPR, ISO27001).
5.  Hence the standard price we quote when asked is $7k.

Thanks in advance for your consideration, please do revert in case of queries if any

**Comment by wparad** [comment]
We can absolutely update the name that is there.

Do you have a link for the auditor cost, a list of auditors and expected price would be great. As many auditors charge > $7k for just the attestation, saying it is $2k is a significant price difference.
